<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <!-- Scrutor for assembly scanning -->
        <PackageReference Include="Scrutor" Version="4.2.2"/>
    </ItemGroup>

    <!-- Project References -->
    <ItemGroup>
        <ProjectReference Include="..\Configuration\Configuration.csproj"/>
        <ProjectReference Include="..\Domain\Domain.csproj"/>
        <ProjectReference Include="..\Shared\Shared.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Analytics\"/>
        <Folder Include="Notifications\"/>
        <Folder Include="Recovery\"/>
    </ItemGroup>
</Project>
